# Generated by Django 5.2.6 on 2025-09-10 06:54

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+85500000000', max_length=128, region='KH'),
            preserve_default=False,
        ),
    ]
