# Generated by Django 5.2.10 on 2026-01-23 05:44

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'The phone number entered is not valid. Please use the format: +855xxxxxxxxx'}, max_length=128, region='KH'),
        ),
    ]
