# Generated by Django 5.2.10 on 2026-01-23 06:01

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'invalid': 'The phone number entered is not valid. Please use format (+855xxxxxxxx)'}, max_length=128, region='KH'),
        ),
    ]
