# Generated by Django 5.2.10 on 2026-01-23 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='The phone number entered is not valid. Please use format (+855xxxxxxxx)', regex='^\\+855\\d{8,9}$')]),
        ),
    ]
